### ISSUE TITLE
CasADi Version

### ISSUE THREAD

**Issue by nog642** [lindseysbrown/brown_circadian_dual-feedback_loop#1]
Hi, I'm trying to run this code, but the CasADi API seems to have changed in newer versions and I can't figure out what version of CasADi this code was originally written with. It seems to be older than 2.4.4, at least.

What version of CasADi should I be using?

**Comment by lindseysbrown** [comment]
Hi, sorry for not having all the version info documented - most of the circadian toolbox stuff was legacy code from the lab.  Unfortunately, I no longer have access to that machine to tell you for sure, but a former lab member thinks it's CasADi 2.3.0 (and noted that he was also never able to get newer versions of CasADi to work either).

Hope that helps!

**Comment by nog642** [comment]
I tried it out and version 2.3.0 seems to have worked. Thank you!

Maybe you could add this to the README.md for anyone in the future?

**Comment by lindseysbrown** [comment]
Great!  And just added the version to the readme as well.
